services:
  transmission:
    image: linuxserver/transmission:4.0.6
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - FILE__USER=/run/secrets/transmission_user
      - FILE__PASS=/run/secrets/transmission_pass
    volumes:
      - transmission:/config
      - /storage/hdd-1/Downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    secrets:
      - transmission_user
      - transmission_pass

secrets:
  transmission_user:
    file: ./.secrets/transmission_user.txt
  transmission_pass:
    file: ./.secrets/transmission_pass.txt

volumes:
  transmission:
