services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./data:/etc/pihole
    ports:
      # DNS Ports
      - 53:53/tcp
      - 53:53/udp
      # Default HTTP Port
      - 10000:80/tcp
      # Default HTTPs Port. FTL will generate a self-signed certificate
      #- 443:443/tcp
