services:
  navidrome:
    image: deluan/navidrome:0.58.0
    user: ${UID}:${GID}
    group_add: ["${GROUP_ID}"]
    container_name: navidrome
    restart: unless-stopped
    environment:
      - ND_DEFAULTLANGUAGE=pt
    volumes:
      - ./data:/data
      - /storage/ssd-1/Músicas:/music:ro
    networks:
      - nginx_net

networks:
  nginx_net:
    external: true
