services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    user: ${UID}:${GID}
    group_add: ["${GROUP_ID}"]
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - ./data:/config
      - ./cache:/cache
      - /storage/hdd-1/video:/media
    networks:
      - nginx_net

networks:
  nginx_net:
    external: true
