services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    user: ${JELLYFIN_UID}:${JELLYFIN_GID}
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - ./data:/config
      - ./cache:/cache
      - /storage/hdd-1/video:/media
    networks:
      - nginx_net

networks:
  nginx_net:
    external: true
